spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aopauth?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false